### ISSUE TITLE
Babel 6 Loose? -- Move to normal

### ISSUE THREAD

**Issue by sldavidson** [DomoApps/starter-kit#24]
See [da-webpack #44](https://git.empdev.domo.com/AppTeam6-Lib/da-webpack/issues/44)

**Comment by sldavidson** [comment]
I have run into a situation with `es2015-Loose` settings.
```javascript
const a = [1,2,2,3,4];
const s = new Set(a);
console.log([...s]) 
```
That should output `[1,2,3,4]` but instead get `[Set]`

Testing this on the [Babel site](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&code=const%20a%20%3D%20%5B1%2C2%2C2%2C3%2C4%5D%3B%0Aconst%20s%20%3D%20new%20Set(a)%3B%0Aconsole.log(%5B...s%5D)) confirms this.

**Comment by andrewjensen** [comment]
+1 let's move to the normal `es2015` preset.

**Comment by bmbarker90** [comment]
Should we remove stage-1 as well? That seems very bleeding-edge to me
