### ISSUE TITLE
Remove all unsafe minification

### ISSUE THREAD

**Issue by jpumford** [DomoApps/starter-kit#38]
I would venture to say that unsafe minification (i.e. removal of unused at-rules) isn't winning us enough in terms of bits and bytes to be worth the bugs we have hunted down. Both @Jonathan-Law and I have spent hours on subtle CSS issues that have arisen from incorrectly minified code.

Can we add `safe: true` to our cssnano config?

**Comment by andrewjensen** [comment]
This sounds good to me!

**Comment by jpumford** [comment]
Solved by #44
