### ISSUE TITLE
Change to production version of Redux?

### ISSUE THREAD

**Issue by jpumford** [DomoApps/starter-kit#42]
I get this error when running the newest version of starter-kit on a production app:
`
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
`

**Comment by sldavidson** [comment]
https://github.com/angular-redux/ng-redux/issues/46

**Comment by bmbarker90** [comment]
Fixed by #45
