### ISSUE TITLE
package.json build script places files incorrectly

### ISSUE THREAD

**Issue by jpumford** [DomoApps/starter-kit#60]
From @hut8:

Minor issue: running `npm run build`, which is:

```
rm -rf ./dist && NODE_ENV=production ./node_modules/.bin/webpack && cp -r domo/ dist/
```

results in the `dist` folder containing a `domo` folder, which contains the thumbnail and manifest.json. Another script, `upload`, has:

```
npm run build && cd dist/ && domo publish && cd ..
```

Because `manifest.json` is in `dist/domo` and not just `dist/`, that ends up causing this error:

```
X No manifest.json file in this directory
Please publish from a directory containing a Custom App design manifest.json file
```

Perhaps the `build` script could just run `cp domo/* dist/` instead?

**Comment by jpumford** [comment]
@hut8
So after looking at the issue a bit, it could be an environment thing that we'll have to fix. What OS are you running/which environment is the `npm build` command running in?

**Comment by hut8** [comment]
Hey! Sorry I somehow missed the notification for this. I'm on Linux (Ubuntu Xenial 16.04).

**Comment by jpumford** [comment]
I've created a pull request which has fixed it on our linux machines. Let me know how that works and I'll get it in advanced-sample-app as well.

**Comment by hut8** [comment]
This can be closed 😄 Thanks for fix.
